### ISSUE TITLE
Incorporate Serverless/Functions into patterns diagram

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/documentation#2083] opened 2024-10-04 13:39 UTC
The patterns diagram needs to be updated to incorporate where Qiskit Serverless and Qiskit Functions fit into the workflow.

**Comment by Eric-Arellano** [comment] 2024-10-04 13:50
Duplicate of https://github.com/Qiskit/documentation/issues/1644

**Closed by Eric-Arellano** 2024-10-04 13:50 UTC
Labels: design 🎨
