### ISSUE TITLE
Image stretches upon click

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#1610] opened 2024-06-27 18:23 UTC
See image in this section: https://docs.quantum.ibm.com/run/system-information#expanded-card-for-a-sample-system

**Comment by Eric-Arellano** [comment] 2024-06-27 19:13
Thanks for opening. Duplicate of https://github.com/Qiskit/documentation/issues/234. We need to make infra improvements here

**Closed by Eric-Arellano** 2024-06-27 19:13 UTC
Labels: content 📄, bug 🐛
