### ISSUE TITLE
Add the development version of Qiskit to API ref?

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#478] opened 2023-12-06 09:49 UTC
I'm think particularly in the run up to 1.0 people might be especially curious to see what's coming in the development version of the API reference. I've also seen other documentation types that they sometimes have a dev version of their api in their historical versions, so it's not a completely novel idea for documentation

**Comment by Eric-Arellano** [comment] 2023-12-06 11:40
Duplicate of https://github.com/Qiskit/documentation/issues/316

**Closed by Eric-Arellano** 2023-12-06 11:40 UTC
Labels: infra 🏗️
