### ISSUE TITLE
Inconsistant notebook options 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/documentation#477] opened 2023-12-05 21:29 UTC
### URL to the relevant documentation

https://docs.quantum.ibm.com/transpile/defaults-and-configuration-options

### Please describe the UI problem.

Some pages have the "download notebook" options like below 
<img width="346" alt="Screenshot 2023-12-05 at 4 29 14 PM" src="https://github.com/Qiskit/documentation/assets/9096989/ae91fc56-df8f-498e-aac1-1d7ccc93cfd2">

While other pages do not have this option: 
<img width="397" alt="Screenshot 2023-12-05 at 4 27 51 PM" src="https://github.com/Qiskit/documentation/assets/9096989/4a07c78a-eeb3-43cb-8d79-b2b09e57627b">

We should try to make this constant across all pages with code cells (in other words, across all pages minus the introduction).

**Comment by Eric-Arellano** [comment] 2023-12-05 21:39
I agree. Duplicate of https://github.com/Qiskit/documentation/issues/169. The other benefit of rewriting to Jupyter notebooks is that it allows us to test if the code has become invalid, whereas we can't test that with MDX unless we invent a bunch of infrastructure we decided we don't want to do.

**Closed by Eric-Arellano** 2023-12-05 21:39 UTC
Labels: UI feedback
