### ISSUE TITLE
Update primitives page for first time users

### ISSUE THREAD

**Issue by jyu00** [Qiskit/documentation#1801] opened 2024-08-05 21:17 UTC
### URL to the relevant documentation

https://docs.quantum.ibm.com/guides/primitives

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

I got some feedback yesterday, from someone who's using primitives for the first time, that the primitives intro page reads like it's only for people who already know about V1 primitive.

For example, instead of describing what sampler/estimator does first, the page immediately jumps to V2 interface changes after "Benefits of Qiskit primitives". Another example is that the description under [SamplerV2](https://docs.quantum.ibm.com/guides/primitives#sampler) says "Sampler V2 is simplified to focus on...". 

Given v1 is support being removed in 10 days, perhaps we can take that opportunity to update the wording.

**Comment by javabster** [comment] 2024-08-08 14:39
closing as duplicate of #1733

**Closed by javabster** 2024-08-08 14:39 UTC
Labels: content 📄, bug 🐛
