### ISSUE TITLE
Add standalone visualizations topic

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#57] opened 2023-09-15 20:56 UTC
Related to [this issue](https://github.com/Qiskit/qiskit/issues/10653), add a standalone page on visualizations to the docs based on [this tutorial](https://qiskit.org/documentation/tutorials/circuits/2_plotting_data_in_qiskit.html). 

Does this topic belong in Build, Test, or Run?

**Comment by javabster** [comment] 2023-10-08 19:35
I think this issue is a duplicate of https://github.com/Qiskit/documentation/issues/43

**Closed by javabster** 2023-10-08 19:35 UTC
Labels: content 📄
