### ISSUE TITLE
Incorrectly displayed primitive result plot in Step 4 of Hello World

### ISSUE THREAD

**Issue by jerrymchow** [Qiskit/documentation#95] opened 2023-10-07 14:25 UTC
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/start/hello-world

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] add new content
- [ ] out-of-date content
- [X] it's just wrong
- [ ] other

### What is the documentation issue/request?

Wrong plot in Step 4 for the code block from Step 3.  Should look like the below. 
<img width="658" alt="Screenshot 2023-10-07 at 10 25 24 AM" src="https://github.com/Qiskit/documentation/assets/28631316/ae224cba-69ca-43f0-9e73-918a50917131">

**Comment by abbycross** [comment] 2023-10-09 15:18
Just now I ran the code both on the simulator and on manila, and both times I got the plot we see in the current version, rather than the one @jerrymchow shows. Anyone know what's wrong in the code? @frankharkins

**Comment by frankharkins** [comment] 2023-10-09 16:08
I also can't reproduce (using `qiskit==0.44.2` and `qiskit_ibm_runtime==0.12.2`). @jerrymchow can you give more information about how you ran the code?

**Comment by abbycross** [comment] 2023-10-10 00:56
I spoke with Jerry and he determined his outcome was different because how he initialized qc -- so our graph is ok, and I'll close this issue. Thanks all!

**Closed by abbycross** 2023-10-10 00:56 UTC
Labels: content 📄
