### ISSUE TITLE
Add version information to non-API ref pages

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#178] opened 2023-10-16 18:13 UTC
Currently there is no way for users to tell if a docs page is using the latest version of Qiskit, Qiskit Runtime or not. We should somehow indicate version information (maybe in a notes box in the bottom?) on each page.

**Comment by Eric-Arellano** [comment] 2023-10-16 19:01
Duplicate of https://github.com/Qiskit/documentation/issues/133.

**Closed by Eric-Arellano** 2023-10-16 19:01 UTC
Labels: infra 🏗️, content 📄, needs discussion 💬
