### ISSUE TITLE
Update "Exact simulation with Qiskit primitives" to use V2 Primitives

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#1072] opened 2024-03-22 15:34 UTC
### Feedback

i.e. StatevectorEstimator and StatevectorSampler

https://docs.quantum.ibm.com/verify/simulate-with-qiskit-primitives

**Comment by javabster** [comment] 2024-03-22 17:19
closing as duplicate of #1025

**Comment by kevinsung** [comment] 2024-03-22 18:28
Actually, this can be done Aer primitives is released since it doesn't use them (it uses the reference primitives in Qiskit itself).

**Comment by kevinsung** [comment] 2024-03-22 18:39
I'd like to first convert the page from MDX to Jupyter notebook, but this is blocked by https://github.com/Qiskit/documentation/pull/812 which modifies the page.

**Closed** 2024-04-19 17:39 UTC
Labels: content 📄, section: transpile 🔀
